version: "3.9"

services:
  influxdb:
    image: "influxdb:2.2-alpine"
    restart: "always"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME="${USER}"
      - DOCKER_INFLUXDB_INIT_PASSWORD="${PASSWORD}"
      - DOCKER_INFLUXDB_INIT_ORG="${ORG}"
      - DOCKER_INFLUXDB_INIT_BUCKET="${BUCKET}"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="${TOKEN}"
    volumes:
      - influxdb-data:/data
    ports:
      - 8086:8086


  logger:
    build: .
    restart: "unless-stopped"
    environment:
      - DOCKER_INFLUXDB_INIT_ORG="${ORG}"
      - DOCKER_INFLUXDB_INIT_BUCKET="${BUCKET}"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN="${TOKEN}"
      - INTERVAL="${INTERVAL}"
    depends_on:
      - "influxdb"
    links:
      - "influxdb"

volumes:
  influxdb-data: