version: "3.7"

services:
  influxdb:
    image: "influxdb:2.2-alpine"
    restart: "always"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=speedtest
      - DOCKER_INFLUXDB_INIT_TOKEN=token
    volumes:
      - influxdb-data:/data
    ports:
      - 8086:8086


#  logger:
#    build: "."
#    depends_on:
#      - "influxdb"

volumes:
  influxdb-data: