version: "3.9"

services:
  influxdb:
    image: "influxdb:2.2-alpine"
    restart: "always"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb-data:/data
    ports:
      - 8086:8086


  logger:
    build: .
    restart: "unless-stopped"
    environment:
      - ORG=${INFLUX_ORG}
      - BUCKET=${INFLUX_BUCKET}
      - TOKEN=${INFLUX_TOKEN}
      - INTERVAL=${INTERVAL}
    depends_on:
      - "influxdb"
    links:
      - "influxdb"

volumes:
  influxdb-data: